# Kết nối MySQL (Tự động tạo DB nếu chưa có)
spring.datasource.url=jdbc:mysql://localhost:3306/pbl3_management?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=NexToue257@

# Hibernate config
spring.jpa.hibernate.ddl-auto=update

# Giúp Spring Boot xử lý việc ghi đè Bean (nếu có xung đột nhỏ giữa Vaadin và Security)
spring.main.allow-bean-definition-overriding=true

# Cấu hình Vaadin để chỉ quét các package cần thiết, tránh xung đột với Spring Security
vaadin.allowed-packages=com.pbl3

# Cấu hình server
server.port=8080


